name: Build Mac DMG

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download JavaFX SDK 21 for macOS
        run: |
          curl -L https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_osx-x64_bin-sdk.zip -o javafx.zip
          unzip javafx.zip
          mv javafx-sdk-21.0.1 javafx

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build JAR using Gradle
        run: ./gradlew clean build --stacktrace

      - name: Build macOS DMG using jpackage
        run: |
          jpackage \
            --name RajdhaniCastingDemoproject \
            --input build/libs \
            --main-jar rajdhaniCastingDemoproject-0.1.0.jar \
            --main-class com.ranjdhaniCastingDemoproject.demo.Main \
            --type dmg \
            --dest output-mac \
            --module-path "javafx/lib" \
            --add-modules javafx.controls,javafx.graphics,javafx.fxml

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RajdhaniCastingDemoproject-mac
          path: output-mac
